# Generated by Django 4.1.12 on 2023-10-16 12:21

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SBCReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SBCReportType', models.CharField(max_length=250)),
                ('Trigger', models.CharField(max_length=250)),
                ('EPTyp', models.CharField(max_length=250)),
                ('SIPCallId', models.CharField(max_length=100)),
                ('SessionId', models.CharField(max_length=100)),
                ('LegId', models.IntegerField()),
                ('Orig', models.CharField(max_length=250)),
                ('SourceIp', models.GenericIPAddressField()),
                ('SourcePort', models.IntegerField()),
                ('DestIp', models.GenericIPAddressField()),
                ('DestPort', models.IntegerField()),
                ('TransportType', models.CharField(max_length=250)),
                ('SrcURI', djongo.models.fields.JSONField()),
                ('SrcURIBeforeMap', models.CharField(max_length=100)),
                ('DstURI', djongo.models.fields.JSONField()),
                ('DstURIBeforeMap', models.CharField(max_length=100)),
                ('Duration', models.IntegerField()),
                ('TrmSd', models.CharField(max_length=250)),
                ('TrmReason', models.CharField(max_length=250)),
                ('TrmReasonCategory', models.CharField(max_length=250)),
                ('SetupTime', models.CharField(max_length=255)),
                ('ConnectTime', models.CharField(max_length=255)),
                ('ReleaseTime', models.CharField(max_length=255)),
                ('RedirectReason', models.IntegerField()),
                ('RedirectURINum', models.CharField(blank=True, max_length=100, null=True)),
                ('RedirectURINumBeforeMap', models.CharField(blank=True, max_length=100, null=True)),
                ('TxSigIPDiffServ', models.IntegerField()),
                ('IPGroup', models.CharField(max_length=250)),
                ('SrdName', models.CharField(max_length=250)),
                ('SIPInterfaceName', models.CharField(max_length=250)),
                ('ProxySetName', models.CharField(max_length=250)),
                ('IpProfileName', models.CharField(max_length=250)),
                ('MediaRealmName', models.CharField(max_length=250)),
                ('DirectMedia', models.CharField(max_length=100)),
                ('SIPTrmReason', models.CharField(max_length=250)),
                ('SIPTermDesc', models.CharField(max_length=100)),
                ('Caller', models.CharField(max_length=250)),
                ('Callee', models.CharField(max_length=250)),
            ],
        ),
    ]
