from djongo import models

# Create your models here.

class SBCReport(models.Model):
    SBCReportType = models.CharField(max_length=250)
    Trigger = models.CharField(max_length=250)
    EPTyp = models.CharField(max_length=250)
    SIPCallId = models.CharField(max_length=100)
    SessionId = models.CharField(max_length=100)
    LegId = models.IntegerField()
    Orig = models.CharField(max_length=250)
    SourceIp = models.GenericIPAddressField()
    SourcePort = models.IntegerField()
    DestIp = models.GenericIPAddressField()
    DestPort = models.IntegerField()
    TransportType = models.CharField(max_length=250)
    SrcURI = models.JSONField()
    SrcURIBeforeMap = models.CharField(max_length=100)
    DstURI = models.JSONField()
    DstURIBeforeMap = models.CharField(max_length=100)
    Duration = models.IntegerField()
    TrmSd = models.CharField(max_length=250)
    TrmReason = models.CharField(max_length=250)
    TrmReasonCategory = models.CharField(max_length=250)
    SetupTime = models.CharField(max_length=255)
    ConnectTime = models.CharField(max_length=255)
    ReleaseTime = models.CharField(max_length=255)
    RedirectReason = models.IntegerField()
    RedirectURINum = models.CharField(max_length=100,blank=True,null=True)
    RedirectURINumBeforeMap = models.CharField(max_length=100,blank=True,null=True)
    TxSigIPDiffServ = models.IntegerField()
    IPGroup = models.CharField(max_length=250)
    SrdName = models.CharField(max_length=250)
    SIPInterfaceName = models.CharField(max_length=250)
    ProxySetName = models.CharField(max_length=250)
    IpProfileName = models.CharField(max_length=250)
    MediaRealmName = models.CharField(max_length=250)
    DirectMedia = models.CharField(max_length=100)
    SIPTrmReason = models.CharField(max_length=250)
    SIPTermDesc = models.CharField(max_length=100)
    Caller = models.CharField(max_length=250)
    Callee = models.CharField(max_length=250)